// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Author struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Book struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	FilePath    string    `json:"file_path"`
	FileSha256  string    `json:"file_sha256"`
	FileSize    int64     `json:"file_size"`
	Format      string    `json:"format"`
	Description string    `json:"description"`
	Publisher   string    `json:"publisher"`
	Language    string    `json:"language"`
	PubDate     string    `json:"pub_date"`
	Series      string    `json:"series"`
	SeriesIndex float64   `json:"series_index"`
	CoverPath   string    `json:"cover_path"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type BookAuthor struct {
	BookID   int64  `json:"book_id"`
	AuthorID int64  `json:"author_id"`
	Role     string `json:"role"`
}

type BooksFt struct {
	Fulltext    string `json:"fulltext"`
	Title       string `json:"title"`
	Series      string `json:"series"`
	Description string `json:"description"`
}
