// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"time"
)

const addBookAuthor = `-- name: AddBookAuthor :exec
INSERT INTO book_authors (book_id, author_id, role)
VALUES (?, ?, ?)
ON CONFLICT(book_id, author_id) DO UPDATE SET role=excluded.role
`

type AddBookAuthorParams struct {
	BookID   int64  `json:"book_id"`
	AuthorID int64  `json:"author_id"`
	Role     string `json:"role"`
}

func (q *Queries) AddBookAuthor(ctx context.Context, arg AddBookAuthorParams) error {
	_, err := q.db.ExecContext(ctx, addBookAuthor, arg.BookID, arg.AuthorID, arg.Role)
	return err
}

const clearBookAuthors = `-- name: ClearBookAuthors :exec
DELETE FROM book_authors
WHERE book_id = ?
`

func (q *Queries) ClearBookAuthors(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, clearBookAuthors, bookID)
	return err
}

const countBooks = `-- name: CountBooks :one
SELECT COUNT(*) FROM books
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchBooksFTS = `-- name: CountSearchBooksFTS :one
SELECT COUNT(*)
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
WHERE books_fts.fulltext MATCH ?
`

func (q *Queries) CountSearchBooksFTS(ctx context.Context, fulltext string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchBooksFTS, fulltext)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=excluded.name
RETURNING id, name, created_at
`

func (q *Queries) CreateAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title, file_path, file_sha256, file_size, format,
    description, publisher, language, pub_date, series,
    series_index, cover_path
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
RETURNING id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at
`

type CreateBookParams struct {
	Title       string  `json:"title"`
	FilePath    string  `json:"file_path"`
	FileSha256  string  `json:"file_sha256"`
	FileSize    int64   `json:"file_size"`
	Format      string  `json:"format"`
	Description string  `json:"description"`
	Publisher   string  `json:"publisher"`
	Language    string  `json:"language"`
	PubDate     string  `json:"pub_date"`
	Series      string  `json:"series"`
	SeriesIndex float64 `json:"series_index"`
	CoverPath   string  `json:"cover_path"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.FilePath,
		arg.FileSha256,
		arg.FileSize,
		arg.Format,
		arg.Description,
		arg.Publisher,
		arg.Language,
		arg.PubDate,
		arg.Series,
		arg.SeriesIndex,
		arg.CoverPath,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING token, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password_hash, role, display_name,
    can_read, can_download, can_upload, can_edit, can_delete
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	DisplayName  string `json:"display_name"`
	CanRead      int64  `json:"can_read"`
	CanDownload  int64  `json:"can_download"`
	CanUpload    int64  `json:"can_upload"`
	CanEdit      int64  `json:"can_edit"`
	CanDelete    int64  `json:"can_delete"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
		arg.CanRead,
		arg.CanDownload,
		arg.CanUpload,
		arg.CanEdit,
		arg.CanDelete,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, created_at FROM authors
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuthorByID(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name, created_at FROM authors
WHERE name = ? LIMIT 1
`

func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAuthorsForBook = `-- name: GetAuthorsForBook :many
SELECT a.id, a.name, a.created_at, ba.role
FROM authors a
JOIN book_authors ba ON a.id = ba.author_id
WHERE ba.book_id = ?
ORDER BY a.name ASC
`

type GetAuthorsForBookRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	Role      string    `json:"role"`
}

func (q *Queries) GetAuthorsForBook(ctx context.Context, bookID int64) ([]GetAuthorsForBookRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthorsForBookRow
	for rows.Next() {
		var i GetAuthorsForBookRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByFilePath = `-- name: GetBookByFilePath :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE file_path = ? LIMIT 1
`

func (q *Queries) GetBookByFilePath(ctx context.Context, filePath string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByFilePath, filePath)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookBySHA256 = `-- name: GetBookBySHA256 :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE file_sha256 = ? LIMIT 1
`

func (q *Queries) GetBookBySHA256(ctx context.Context, fileSha256 string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookBySHA256, fileSha256)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgress = `-- name: GetProgress :one
SELECT user_id, book_id, location, progress, current_page, total_pages, is_finished, updated_at FROM reading_progress
WHERE user_id = ? AND book_id = ? LIMIT 1
`

type GetProgressParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getProgress, arg.UserID, arg.BookID)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Location,
		&i.Progress,
		&i.CurrentPage,
		&i.TotalPages,
		&i.IsFinished,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.token, s.user_id, s.expires_at, u.username, u.role, u.display_name,
       u.can_read, u.can_download, u.can_upload, u.can_edit, u.can_delete
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = ? AND s.expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

type GetSessionWithUserRow struct {
	Token       string    `json:"token"`
	UserID      int64     `json:"user_id"`
	ExpiresAt   time.Time `json:"expires_at"`
	Username    string    `json:"username"`
	Role        string    `json:"role"`
	DisplayName string    `json:"display_name"`
	CanRead     int64     `json:"can_read"`
	CanDownload int64     `json:"can_download"`
	CanUpload   int64     `json:"can_upload"`
	CanEdit     int64     `json:"can_edit"`
	CanDelete   int64     `json:"can_delete"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, token)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.Username,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, created_at FROM authors
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListAuthorsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListBooksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksWithAuthors = `-- name: ListBooksWithAuthors :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names
FROM books b
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
GROUP BY b.id
ORDER BY b.id DESC
LIMIT ? OFFSET ?
`

type ListBooksWithAuthorsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListBooksWithAuthorsRow struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	FilePath    string      `json:"file_path"`
	FileSha256  string      `json:"file_sha256"`
	FileSize    int64       `json:"file_size"`
	Format      string      `json:"format"`
	Description string      `json:"description"`
	Publisher   string      `json:"publisher"`
	Language    string      `json:"language"`
	PubDate     string      `json:"pub_date"`
	Series      string      `json:"series"`
	SeriesIndex float64     `json:"series_index"`
	CoverPath   string      `json:"cover_path"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	AuthorNames interface{} `json:"author_names"`
}

func (q *Queries) ListBooksWithAuthors(ctx context.Context, arg ListBooksWithAuthorsParams) ([]ListBooksWithAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksWithAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksWithAuthorsRow
	for rows.Next() {
		var i ListBooksWithAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksWithAuthorsAndProgress = `-- name: ListBooksWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
GROUP BY b.id
ORDER BY b.id DESC
LIMIT ? OFFSET ?
`

type ListBooksWithAuthorsAndProgressParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListBooksWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

func (q *Queries) ListBooksWithAuthorsAndProgress(ctx context.Context, arg ListBooksWithAuthorsAndProgressParams) ([]ListBooksWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksWithAuthorsAndProgress, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksWithAuthorsAndProgressRow
	for rows.Next() {
		var i ListBooksWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProgressByUserID = `-- name: ListRecentProgressByUserID :many
SELECT
    rp.user_id, rp.book_id, rp.location, rp.progress, rp.current_page, rp.total_pages, rp.is_finished, rp.updated_at,
    b.title, b.file_path, b.file_size, b.format, b.cover_path,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names
FROM reading_progress rp
JOIN books b ON rp.book_id = b.id
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
WHERE rp.user_id = ? AND rp.is_finished = 0 AND rp.progress > 0
GROUP BY b.id
ORDER BY rp.updated_at DESC
LIMIT ?
`

type ListRecentProgressByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

type ListRecentProgressByUserIDRow struct {
	UserID      int64       `json:"user_id"`
	BookID      int64       `json:"book_id"`
	Location    string      `json:"location"`
	Progress    float64     `json:"progress"`
	CurrentPage int64       `json:"current_page"`
	TotalPages  int64       `json:"total_pages"`
	IsFinished  int64       `json:"is_finished"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Title       string      `json:"title"`
	FilePath    string      `json:"file_path"`
	FileSize    int64       `json:"file_size"`
	Format      string      `json:"format"`
	CoverPath   string      `json:"cover_path"`
	AuthorNames interface{} `json:"author_names"`
}

func (q *Queries) ListRecentProgressByUserID(ctx context.Context, arg ListRecentProgressByUserIDParams) ([]ListRecentProgressByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentProgressByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentProgressByUserIDRow
	for rows.Next() {
		var i ListRecentProgressByUserIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.BookID,
			&i.Location,
			&i.Progress,
			&i.CurrentPage,
			&i.TotalPages,
			&i.IsFinished,
			&i.UpdatedAt,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.Format,
			&i.CoverPath,
			&i.AuthorNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, display_name,
       can_read, can_download, can_upload, can_edit, can_delete,
       created_at, updated_at
FROM users
ORDER BY id ASC
`

type ListUsersRow struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	Role        string    `json:"role"`
	DisplayName string    `json:"display_name"`
	CanRead     int64     `json:"can_read"`
	CanDownload int64     `json:"can_download"`
	CanUpload   int64     `json:"can_upload"`
	CanEdit     int64     `json:"can_edit"`
	CanDelete   int64     `json:"can_delete"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.DisplayName,
			&i.CanRead,
			&i.CanDownload,
			&i.CanUpload,
			&i.CanEdit,
			&i.CanDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksFTS = `-- name: SearchBooksFTS :many
SELECT b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format, b.description, b.publisher, b.language, b.pub_date, b.series, b.series_index, b.cover_path, b.created_at, b.updated_at
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
WHERE books_fts.fulltext MATCH ?
ORDER BY books_fts.rank
LIMIT ? OFFSET ?
`

type SearchBooksFTSParams struct {
	Fulltext string `json:"fulltext"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) SearchBooksFTS(ctx context.Context, arg SearchBooksFTSParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksFTS, arg.Fulltext, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksFTSWithAuthors = `-- name: SearchBooksFTSWithAuthors :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
WHERE books_fts.fulltext MATCH ?
GROUP BY b.id
ORDER BY books_fts.rank
LIMIT ? OFFSET ?
`

type SearchBooksFTSWithAuthorsParams struct {
	Fulltext string `json:"fulltext"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type SearchBooksFTSWithAuthorsRow struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	FilePath    string      `json:"file_path"`
	FileSha256  string      `json:"file_sha256"`
	FileSize    int64       `json:"file_size"`
	Format      string      `json:"format"`
	Description string      `json:"description"`
	Publisher   string      `json:"publisher"`
	Language    string      `json:"language"`
	PubDate     string      `json:"pub_date"`
	Series      string      `json:"series"`
	SeriesIndex float64     `json:"series_index"`
	CoverPath   string      `json:"cover_path"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	AuthorNames interface{} `json:"author_names"`
}

func (q *Queries) SearchBooksFTSWithAuthors(ctx context.Context, arg SearchBooksFTSWithAuthorsParams) ([]SearchBooksFTSWithAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksFTSWithAuthors, arg.Fulltext, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksFTSWithAuthorsRow
	for rows.Next() {
		var i SearchBooksFTSWithAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksFTSWithAuthorsAndProgress = `-- name: SearchBooksFTSWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
WHERE books_fts.fulltext MATCH ?
GROUP BY b.id
ORDER BY books_fts.rank
LIMIT ? OFFSET ?
`

type SearchBooksFTSWithAuthorsAndProgressParams struct {
	UserID   int64  `json:"user_id"`
	Fulltext string `json:"fulltext"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type SearchBooksFTSWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

func (q *Queries) SearchBooksFTSWithAuthorsAndProgress(ctx context.Context, arg SearchBooksFTSWithAuthorsAndProgressParams) ([]SearchBooksFTSWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksFTSWithAuthorsAndProgress,
		arg.UserID,
		arg.Fulltext,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksFTSWithAuthorsAndProgressRow
	for rows.Next() {
		var i SearchBooksFTSWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookMetadata = `-- name: UpdateBookMetadata :one
UPDATE books
SET title = ?,
    description = ?,
    publisher = ?,
    language = ?,
    pub_date = ?,
    series = ?,
    series_index = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at
`

type UpdateBookMetadataParams struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Publisher   string  `json:"publisher"`
	Language    string  `json:"language"`
	PubDate     string  `json:"pub_date"`
	Series      string  `json:"series"`
	SeriesIndex float64 `json:"series_index"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateBookMetadata(ctx context.Context, arg UpdateBookMetadataParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBookMetadata,
		arg.Title,
		arg.Description,
		arg.Publisher,
		arg.Language,
		arg.PubDate,
		arg.Series,
		arg.SeriesIndex,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = ?,
    role = ?,
    can_read = ?,
    can_download = ?,
    can_upload = ?,
    can_edit = ?,
    can_delete = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at
`

type UpdateUserParams struct {
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	CanRead     int64  `json:"can_read"`
	CanDownload int64  `json:"can_download"`
	CanUpload   int64  `json:"can_upload"`
	CanEdit     int64  `json:"can_edit"`
	CanDelete   int64  `json:"can_delete"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.DisplayName,
		arg.Role,
		arg.CanRead,
		arg.CanDownload,
		arg.CanUpload,
		arg.CanEdit,
		arg.CanDelete,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProgress = `-- name: UpsertProgress :one
INSERT INTO reading_progress (
    user_id, book_id, location, progress, current_page, total_pages, is_finished, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
)
ON CONFLICT(user_id, book_id) DO UPDATE SET
    location = excluded.location,
    progress = excluded.progress,
    current_page = excluded.current_page,
    total_pages = excluded.total_pages,
    is_finished = excluded.is_finished,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, book_id, location, progress, current_page, total_pages, is_finished, updated_at
`

type UpsertProgressParams struct {
	UserID      int64   `json:"user_id"`
	BookID      int64   `json:"book_id"`
	Location    string  `json:"location"`
	Progress    float64 `json:"progress"`
	CurrentPage int64   `json:"current_page"`
	TotalPages  int64   `json:"total_pages"`
	IsFinished  int64   `json:"is_finished"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertProgress,
		arg.UserID,
		arg.BookID,
		arg.Location,
		arg.Progress,
		arg.CurrentPage,
		arg.TotalPages,
		arg.IsFinished,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Location,
		&i.Progress,
		&i.CurrentPage,
		&i.TotalPages,
		&i.IsFinished,
		&i.UpdatedAt,
	)
	return i, err
}
