// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
	"time"
)

const addBookAuthor = `-- name: AddBookAuthor :exec
INSERT INTO book_authors (book_id, author_id, role)
VALUES (?, ?, ?)
ON CONFLICT(book_id, author_id) DO UPDATE SET role=excluded.role
`

type AddBookAuthorParams struct {
	BookID   int64  `json:"book_id"`
	AuthorID int64  `json:"author_id"`
	Role     string `json:"role"`
}

func (q *Queries) AddBookAuthor(ctx context.Context, arg AddBookAuthorParams) error {
	_, err := q.db.ExecContext(ctx, addBookAuthor, arg.BookID, arg.AuthorID, arg.Role)
	return err
}

const addBookTag = `-- name: AddBookTag :exec
INSERT INTO book_tags (book_id, tag_id)
VALUES (?, ?)
ON CONFLICT(book_id, tag_id) DO NOTHING
`

type AddBookTagParams struct {
	BookID int64 `json:"book_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddBookTag(ctx context.Context, arg AddBookTagParams) error {
	_, err := q.db.ExecContext(ctx, addBookTag, arg.BookID, arg.TagID)
	return err
}

const addBookToShelf = `-- name: AddBookToShelf :exec
INSERT OR IGNORE INTO shelf_books (shelf_id, book_id)
VALUES (?, ?)
`

type AddBookToShelfParams struct {
	ShelfID int64 `json:"shelf_id"`
	BookID  int64 `json:"book_id"`
}

func (q *Queries) AddBookToShelf(ctx context.Context, arg AddBookToShelfParams) error {
	_, err := q.db.ExecContext(ctx, addBookToShelf, arg.ShelfID, arg.BookID)
	return err
}

const clearBookAuthors = `-- name: ClearBookAuthors :exec
DELETE FROM book_authors
WHERE book_id = ?
`

func (q *Queries) ClearBookAuthors(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, clearBookAuthors, bookID)
	return err
}

const clearBookTags = `-- name: ClearBookTags :exec
DELETE FROM book_tags
WHERE book_id = ?
`

func (q *Queries) ClearBookTags(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, clearBookTags, bookID)
	return err
}

const countBooks = `-- name: CountBooks :one
SELECT COUNT(*) FROM books
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBooksByAuthor = `-- name: CountBooksByAuthor :one
SELECT COUNT(DISTINCT b.id)
FROM books b
JOIN book_authors ba ON b.id = ba.book_id
JOIN authors a ON ba.author_id = a.id
WHERE a.name = ?
`

func (q *Queries) CountBooksByAuthor(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksByAuthor, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBooksByFormat = `-- name: CountBooksByFormat :one
SELECT COUNT(id) FROM books WHERE format = ?
`

func (q *Queries) CountBooksByFormat(ctx context.Context, format string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksByFormat, format)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBooksBySeries = `-- name: CountBooksBySeries :one
SELECT COUNT(b.id)
FROM books b
WHERE b.series = ? COLLATE NOCASE
`

func (q *Queries) CountBooksBySeries(ctx context.Context, series string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksBySeries, series)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBooksByShelf = `-- name: CountBooksByShelf :one
SELECT COUNT(*)
FROM shelf_books
WHERE shelf_id = ?
`

func (q *Queries) CountBooksByShelf(ctx context.Context, shelfID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksByShelf, shelfID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBooksByTag = `-- name: CountBooksByTag :one
SELECT COUNT(DISTINCT b.id)
FROM books b
JOIN book_tags bt ON b.id = bt.book_id
JOIN tags t ON bt.tag_id = t.id
WHERE t.name = ?
`

func (q *Queries) CountBooksByTag(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooksByTag, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchBooksFTS = `-- name: CountSearchBooksFTS :one
SELECT COUNT(*)
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
WHERE books_fts.fulltext MATCH ?
`

func (q *Queries) CountSearchBooksFTS(ctx context.Context, fulltext string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchBooksFTS, fulltext)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=excluded.name
RETURNING id, name, created_at
`

func (q *Queries) CreateAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title, file_path, file_sha256, file_size, format,
    description, publisher, language, pub_date, series,
    series_index, cover_path
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
RETURNING id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at
`

type CreateBookParams struct {
	Title       string  `json:"title"`
	FilePath    string  `json:"file_path"`
	FileSha256  string  `json:"file_sha256"`
	FileSize    int64   `json:"file_size"`
	Format      string  `json:"format"`
	Description string  `json:"description"`
	Publisher   string  `json:"publisher"`
	Language    string  `json:"language"`
	PubDate     string  `json:"pub_date"`
	Series      string  `json:"series"`
	SeriesIndex float64 `json:"series_index"`
	CoverPath   string  `json:"cover_path"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.FilePath,
		arg.FileSha256,
		arg.FileSize,
		arg.Format,
		arg.Description,
		arg.Publisher,
		arg.Language,
		arg.PubDate,
		arg.Series,
		arg.SeriesIndex,
		arg.CoverPath,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (
    user_id, book_id, title, location, progress, created_at
) VALUES (
    ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
)
RETURNING id, user_id, book_id, title, location, progress, created_at
`

type CreateBookmarkParams struct {
	UserID   int64   `json:"user_id"`
	BookID   int64   `json:"book_id"`
	Title    string  `json:"title"`
	Location string  `json:"location"`
	Progress float64 `json:"progress"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.UserID,
		arg.BookID,
		arg.Title,
		arg.Location,
		arg.Progress,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Location,
		&i.Progress,
		&i.CreatedAt,
	)
	return i, err
}

const createHighlight = `-- name: CreateHighlight :one
INSERT INTO highlights (
    user_id, book_id, location, selected_text, note, color, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
RETURNING id, user_id, book_id, location, selected_text, note, color, created_at, updated_at
`

type CreateHighlightParams struct {
	UserID       int64  `json:"user_id"`
	BookID       int64  `json:"book_id"`
	Location     string `json:"location"`
	SelectedText string `json:"selected_text"`
	Note         string `json:"note"`
	Color        string `json:"color"`
}

func (q *Queries) CreateHighlight(ctx context.Context, arg CreateHighlightParams) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, createHighlight,
		arg.UserID,
		arg.BookID,
		arg.Location,
		arg.SelectedText,
		arg.Note,
		arg.Color,
	)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Location,
		&i.SelectedText,
		&i.Note,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING token, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createShelf = `-- name: CreateShelf :one
INSERT INTO shelves (user_id, name, description, is_public)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, name, description, is_public, created_at, updated_at
`

type CreateShelfParams struct {
	UserID      int64  `json:"user_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsPublic    int64  `json:"is_public"`
}

func (q *Queries) CreateShelf(ctx context.Context, arg CreateShelfParams) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, createShelf,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.IsPublic,
	)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=excluded.name
RETURNING id, name, created_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password_hash, role, display_name,
    can_read, can_download, can_upload, can_edit, can_delete
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	DisplayName  string `json:"display_name"`
	CanRead      int64  `json:"can_read"`
	CanDownload  int64  `json:"can_download"`
	CanUpload    int64  `json:"can_upload"`
	CanEdit      int64  `json:"can_edit"`
	CanDelete    int64  `json:"can_delete"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
		arg.CanRead,
		arg.CanDownload,
		arg.CanUpload,
		arg.CanEdit,
		arg.CanDelete,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const deleteBookRating = `-- name: DeleteBookRating :exec
DELETE FROM book_ratings
WHERE user_id = ? AND book_id = ?
`

type DeleteBookRatingParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) DeleteBookRating(ctx context.Context, arg DeleteBookRatingParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookRating, arg.UserID, arg.BookID)
	return err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks
WHERE id = ? AND user_id = ?
`

type DeleteBookmarkParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, arg.ID, arg.UserID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteHighlight = `-- name: DeleteHighlight :exec
DELETE FROM highlights
WHERE id = ? AND user_id = ?
`

type DeleteHighlightParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteHighlight(ctx context.Context, arg DeleteHighlightParams) error {
	_, err := q.db.ExecContext(ctx, deleteHighlight, arg.ID, arg.UserID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteShelf = `-- name: DeleteShelf :exec
DELETE FROM shelves
WHERE id = ? AND user_id = ?
`

type DeleteShelfParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteShelf(ctx context.Context, arg DeleteShelfParams) error {
	_, err := q.db.ExecContext(ctx, deleteShelf, arg.ID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, created_at FROM authors
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuthorByID(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name, created_at FROM authors
WHERE name = ? LIMIT 1
`

func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAuthorsForBook = `-- name: GetAuthorsForBook :many
SELECT a.id, a.name, a.created_at, ba.role
FROM authors a
JOIN book_authors ba ON a.id = ba.author_id
WHERE ba.book_id = ?
ORDER BY a.name ASC
`

type GetAuthorsForBookRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	Role      string    `json:"role"`
}

func (q *Queries) GetAuthorsForBook(ctx context.Context, bookID int64) ([]GetAuthorsForBookRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthorsForBookRow
	for rows.Next() {
		var i GetAuthorsForBookRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookAverageRating = `-- name: GetBookAverageRating :one
SELECT 
    coalesce(AVG(rating), 0.0) as avg_rating,
    COUNT(rating) as rating_count
FROM book_ratings
WHERE book_id = ?
`

type GetBookAverageRatingRow struct {
	AvgRating   interface{} `json:"avg_rating"`
	RatingCount int64       `json:"rating_count"`
}

func (q *Queries) GetBookAverageRating(ctx context.Context, bookID int64) (GetBookAverageRatingRow, error) {
	row := q.db.QueryRowContext(ctx, getBookAverageRating, bookID)
	var i GetBookAverageRatingRow
	err := row.Scan(&i.AvgRating, &i.RatingCount)
	return i, err
}

const getBookByFilePath = `-- name: GetBookByFilePath :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE file_path = ? LIMIT 1
`

func (q *Queries) GetBookByFilePath(ctx context.Context, filePath string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByFilePath, filePath)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookBySHA256 = `-- name: GetBookBySHA256 :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE file_sha256 = ? LIMIT 1
`

func (q *Queries) GetBookBySHA256(ctx context.Context, fileSha256 string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookBySHA256, fileSha256)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookRatingForUser = `-- name: GetBookRatingForUser :one
SELECT rating FROM book_ratings
WHERE user_id = ? AND book_id = ? LIMIT 1
`

type GetBookRatingForUserParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) GetBookRatingForUser(ctx context.Context, arg GetBookRatingForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBookRatingForUser, arg.UserID, arg.BookID)
	var rating int64
	err := row.Scan(&rating)
	return rating, err
}

const getBookShelfIDsForUser = `-- name: GetBookShelfIDsForUser :many
SELECT sb.shelf_id
FROM shelf_books sb
JOIN shelves s ON sb.shelf_id = s.id
WHERE sb.book_id = ? AND s.user_id = ?
`

type GetBookShelfIDsForUserParams struct {
	BookID int64 `json:"book_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetBookShelfIDsForUser(ctx context.Context, arg GetBookShelfIDsForUserParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getBookShelfIDsForUser, arg.BookID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var shelf_id int64
		if err := rows.Scan(&shelf_id); err != nil {
			return nil, err
		}
		items = append(items, shelf_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarkByID = `-- name: GetBookmarkByID :one
SELECT id, user_id, book_id, title, location, progress, created_at FROM bookmarks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookmarkByID(ctx context.Context, id int64) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByID, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Title,
		&i.Location,
		&i.Progress,
		&i.CreatedAt,
	)
	return i, err
}

const getHighlightByID = `-- name: GetHighlightByID :one
SELECT id, user_id, book_id, location, selected_text, note, color, created_at, updated_at FROM highlights
WHERE id = ? LIMIT 1
`

func (q *Queries) GetHighlightByID(ctx context.Context, id int64) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, getHighlightByID, id)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Location,
		&i.SelectedText,
		&i.Note,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgress = `-- name: GetProgress :one
SELECT user_id, book_id, location, progress, current_page, total_pages, is_finished, updated_at FROM reading_progress
WHERE user_id = ? AND book_id = ? LIMIT 1
`

type GetProgressParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getProgress, arg.UserID, arg.BookID)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Location,
		&i.Progress,
		&i.CurrentPage,
		&i.TotalPages,
		&i.IsFinished,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.token, s.user_id, s.expires_at, u.username, u.role, u.display_name,
       u.can_read, u.can_download, u.can_upload, u.can_edit, u.can_delete
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = ? AND s.expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

type GetSessionWithUserRow struct {
	Token       string    `json:"token"`
	UserID      int64     `json:"user_id"`
	ExpiresAt   time.Time `json:"expires_at"`
	Username    string    `json:"username"`
	Role        string    `json:"role"`
	DisplayName string    `json:"display_name"`
	CanRead     int64     `json:"can_read"`
	CanDownload int64     `json:"can_download"`
	CanUpload   int64     `json:"can_upload"`
	CanEdit     int64     `json:"can_edit"`
	CanDelete   int64     `json:"can_delete"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, token)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.Username,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
	)
	return i, err
}

const getShelfByID = `-- name: GetShelfByID :one
SELECT id, user_id, name, description, is_public, created_at, updated_at FROM shelves
WHERE id = ? LIMIT 1
`

func (q *Queries) GetShelfByID(ctx context.Context, id int64) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, getShelfByID, id)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShelfByNameAndUser = `-- name: GetShelfByNameAndUser :one
SELECT id, user_id, name, description, is_public, created_at, updated_at FROM shelves
WHERE user_id = ? AND name = ? LIMIT 1
`

type GetShelfByNameAndUserParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetShelfByNameAndUser(ctx context.Context, arg GetShelfByNameAndUserParams) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, getShelfByNameAndUser, arg.UserID, arg.Name)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, created_at FROM tags
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags
WHERE name = ? LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagsForBook = `-- name: GetTagsForBook :many
SELECT t.id, t.name, t.created_at
FROM tags t
JOIN book_tags bt ON t.id = bt.tag_id
WHERE bt.book_id = ?
ORDER BY t.name ASC
`

func (q *Queries) GetTagsForBook(ctx context.Context, bookID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, created_at FROM authors
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListAuthorsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsWithBookCount = `-- name: ListAuthorsWithBookCount :many
SELECT a.id, a.name, a.created_at, COUNT(DISTINCT ba.book_id) as book_count
FROM authors a
JOIN book_authors ba ON a.id = ba.author_id
GROUP BY a.id
HAVING book_count > 0
ORDER BY a.name COLLATE NOCASE ASC
`

type ListAuthorsWithBookCountRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	BookCount int64     `json:"book_count"`
}

func (q *Queries) ListAuthorsWithBookCount(ctx context.Context) ([]ListAuthorsWithBookCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorsWithBookCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsWithBookCountRow
	for rows.Next() {
		var i ListAuthorsWithBookCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookmarksForUserAndBook = `-- name: ListBookmarksForUserAndBook :many
SELECT id, user_id, book_id, title, location, progress, created_at FROM bookmarks
WHERE user_id = ? AND book_id = ?
ORDER BY created_at DESC
`

type ListBookmarksForUserAndBookParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

// Bookmarks queries
func (q *Queries) ListBookmarksForUserAndBook(ctx context.Context, arg ListBookmarksForUserAndBookParams) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarksForUserAndBook, arg.UserID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Title,
			&i.Location,
			&i.Progress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListBooksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByAuthorWithAuthorsAndProgress = `-- name: ListBooksByAuthorWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce((SELECT GROUP_CONCAT(a2.name, ', ') FROM book_authors ba2 JOIN authors a2 ON ba2.author_id = a2.id WHERE ba2.book_id = b.id), '') as author_names,
    coalesce((SELECT GROUP_CONCAT(t.name, ', ') FROM book_tags bt JOIN tags t ON bt.tag_id = t.id WHERE bt.book_id = b.id), '') as tag_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
JOIN book_authors ba ON b.id = ba.book_id
JOIN authors a ON ba.author_id = a.id
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
WHERE a.name = ?
GROUP BY b.id
ORDER BY b.id DESC
LIMIT ? OFFSET ?
`

type ListBooksByAuthorWithAuthorsAndProgressParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListBooksByAuthorWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	TagNames       interface{} `json:"tag_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

func (q *Queries) ListBooksByAuthorWithAuthorsAndProgress(ctx context.Context, arg ListBooksByAuthorWithAuthorsAndProgressParams) ([]ListBooksByAuthorWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByAuthorWithAuthorsAndProgress,
		arg.UserID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByAuthorWithAuthorsAndProgressRow
	for rows.Next() {
		var i ListBooksByAuthorWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.TagNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByFormatWithAuthorsAndProgress = `-- name: ListBooksByFormatWithAuthorsAndProgress :many

SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce((SELECT GROUP_CONCAT(a.name, ', ') FROM book_authors ba JOIN authors a ON ba.author_id = a.id WHERE ba.book_id = b.id), '') as author_names,
    coalesce((SELECT GROUP_CONCAT(t.name, ', ') FROM book_tags bt JOIN tags t ON bt.tag_id = t.id WHERE bt.book_id = b.id), '') as tag_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
WHERE b.format = ?
ORDER BY b.id DESC
LIMIT ? OFFSET ?
`

type ListBooksByFormatWithAuthorsAndProgressParams struct {
	UserID int64  `json:"user_id"`
	Format string `json:"format"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListBooksByFormatWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	TagNames       interface{} `json:"tag_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

// ============================================================================
// Format Filtering Queries
// ============================================================================
func (q *Queries) ListBooksByFormatWithAuthorsAndProgress(ctx context.Context, arg ListBooksByFormatWithAuthorsAndProgressParams) ([]ListBooksByFormatWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByFormatWithAuthorsAndProgress,
		arg.UserID,
		arg.Format,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByFormatWithAuthorsAndProgressRow
	for rows.Next() {
		var i ListBooksByFormatWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.TagNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksBySeriesWithAuthorsAndProgress = `-- name: ListBooksBySeriesWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce((SELECT GROUP_CONCAT(a2.name, ', ') FROM book_authors ba2 JOIN authors a2 ON ba2.author_id = a2.id WHERE ba2.book_id = b.id), '') as author_names,
    coalesce((SELECT GROUP_CONCAT(t.name, ', ') FROM book_tags bt JOIN tags t ON bt.tag_id = t.id WHERE bt.book_id = b.id), '') as tag_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
WHERE b.series = ? COLLATE NOCASE
ORDER BY b.series_index ASC, b.id ASC
LIMIT ? OFFSET ?
`

type ListBooksBySeriesWithAuthorsAndProgressParams struct {
	UserID int64  `json:"user_id"`
	Series string `json:"series"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListBooksBySeriesWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	TagNames       interface{} `json:"tag_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

func (q *Queries) ListBooksBySeriesWithAuthorsAndProgress(ctx context.Context, arg ListBooksBySeriesWithAuthorsAndProgressParams) ([]ListBooksBySeriesWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksBySeriesWithAuthorsAndProgress,
		arg.UserID,
		arg.Series,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksBySeriesWithAuthorsAndProgressRow
	for rows.Next() {
		var i ListBooksBySeriesWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.TagNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByShelfWithAuthorsAndProgress = `-- name: ListBooksByShelfWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce((SELECT GROUP_CONCAT(a.name, ', ') FROM book_authors ba JOIN authors a ON ba.author_id = a.id WHERE ba.book_id = b.id), '') as author_names,
    coalesce((SELECT GROUP_CONCAT(t.name, ', ') FROM book_tags bt JOIN tags t ON bt.tag_id = t.id WHERE bt.book_id = b.id), '') as tag_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished,
    sb.added_at as shelf_added_at
FROM shelf_books sb
JOIN books b ON sb.book_id = b.id
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
WHERE sb.shelf_id = ?
ORDER BY sb.added_at DESC
LIMIT ? OFFSET ?
`

type ListBooksByShelfWithAuthorsAndProgressParams struct {
	UserID  int64 `json:"user_id"`
	ShelfID int64 `json:"shelf_id"`
	Limit   int64 `json:"limit"`
	Offset  int64 `json:"offset"`
}

type ListBooksByShelfWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	TagNames       interface{} `json:"tag_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
	ShelfAddedAt   time.Time   `json:"shelf_added_at"`
}

func (q *Queries) ListBooksByShelfWithAuthorsAndProgress(ctx context.Context, arg ListBooksByShelfWithAuthorsAndProgressParams) ([]ListBooksByShelfWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByShelfWithAuthorsAndProgress,
		arg.UserID,
		arg.ShelfID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByShelfWithAuthorsAndProgressRow
	for rows.Next() {
		var i ListBooksByShelfWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.TagNames,
			&i.UserProgress,
			&i.UserIsFinished,
			&i.ShelfAddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByTagWithAuthorsAndProgress = `-- name: ListBooksByTagWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce((SELECT GROUP_CONCAT(a.name, ', ') FROM book_authors ba JOIN authors a ON ba.author_id = a.id WHERE ba.book_id = b.id), '') as author_names,
    coalesce((SELECT GROUP_CONCAT(t.name, ', ') FROM book_tags bt JOIN tags t ON bt.tag_id = t.id WHERE bt.book_id = b.id), '') as tag_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
JOIN book_tags bt ON b.id = bt.book_id
JOIN tags t ON bt.tag_id = t.id
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
WHERE t.name = ?
GROUP BY b.id
ORDER BY b.id DESC
LIMIT ? OFFSET ?
`

type ListBooksByTagWithAuthorsAndProgressParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListBooksByTagWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	TagNames       interface{} `json:"tag_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

func (q *Queries) ListBooksByTagWithAuthorsAndProgress(ctx context.Context, arg ListBooksByTagWithAuthorsAndProgressParams) ([]ListBooksByTagWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByTagWithAuthorsAndProgress,
		arg.UserID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksByTagWithAuthorsAndProgressRow
	for rows.Next() {
		var i ListBooksByTagWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.TagNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksWithAuthors = `-- name: ListBooksWithAuthors :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names
FROM books b
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
GROUP BY b.id
ORDER BY b.id DESC
LIMIT ? OFFSET ?
`

type ListBooksWithAuthorsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListBooksWithAuthorsRow struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	FilePath    string      `json:"file_path"`
	FileSha256  string      `json:"file_sha256"`
	FileSize    int64       `json:"file_size"`
	Format      string      `json:"format"`
	Description string      `json:"description"`
	Publisher   string      `json:"publisher"`
	Language    string      `json:"language"`
	PubDate     string      `json:"pub_date"`
	Series      string      `json:"series"`
	SeriesIndex float64     `json:"series_index"`
	CoverPath   string      `json:"cover_path"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	AuthorNames interface{} `json:"author_names"`
}

func (q *Queries) ListBooksWithAuthors(ctx context.Context, arg ListBooksWithAuthorsParams) ([]ListBooksWithAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksWithAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksWithAuthorsRow
	for rows.Next() {
		var i ListBooksWithAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksWithAuthorsAndProgress = `-- name: ListBooksWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce((SELECT GROUP_CONCAT(a.name, ', ') FROM book_authors ba JOIN authors a ON ba.author_id = a.id WHERE ba.book_id = b.id), '') as author_names,
    coalesce((SELECT GROUP_CONCAT(t.name, ', ') FROM book_tags bt JOIN tags t ON bt.tag_id = t.id WHERE bt.book_id = b.id), '') as tag_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
GROUP BY b.id
ORDER BY b.id DESC
LIMIT ? OFFSET ?
`

type ListBooksWithAuthorsAndProgressParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListBooksWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	TagNames       interface{} `json:"tag_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

func (q *Queries) ListBooksWithAuthorsAndProgress(ctx context.Context, arg ListBooksWithAuthorsAndProgressParams) ([]ListBooksWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, listBooksWithAuthorsAndProgress, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksWithAuthorsAndProgressRow
	for rows.Next() {
		var i ListBooksWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.TagNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsForUserAndBook = `-- name: ListHighlightsForUserAndBook :many
SELECT id, user_id, book_id, location, selected_text, note, color, created_at, updated_at FROM highlights
WHERE user_id = ? AND book_id = ?
ORDER BY created_at DESC
`

type ListHighlightsForUserAndBookParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
}

// Highlights & Notes queries
func (q *Queries) ListHighlightsForUserAndBook(ctx context.Context, arg ListHighlightsForUserAndBookParams) ([]Highlight, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsForUserAndBook, arg.UserID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.Location,
			&i.SelectedText,
			&i.Note,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProgressByUserID = `-- name: ListRecentProgressByUserID :many
SELECT
    rp.user_id, rp.book_id, rp.location, rp.progress, rp.current_page, rp.total_pages, rp.is_finished, rp.updated_at,
    b.title, b.file_path, b.file_size, b.format, b.cover_path,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names
FROM reading_progress rp
JOIN books b ON rp.book_id = b.id
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
WHERE rp.user_id = ? AND rp.is_finished = 0 AND rp.progress > 0
GROUP BY b.id
ORDER BY rp.updated_at DESC
LIMIT ?
`

type ListRecentProgressByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
}

type ListRecentProgressByUserIDRow struct {
	UserID      int64       `json:"user_id"`
	BookID      int64       `json:"book_id"`
	Location    string      `json:"location"`
	Progress    float64     `json:"progress"`
	CurrentPage int64       `json:"current_page"`
	TotalPages  int64       `json:"total_pages"`
	IsFinished  int64       `json:"is_finished"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Title       string      `json:"title"`
	FilePath    string      `json:"file_path"`
	FileSize    int64       `json:"file_size"`
	Format      string      `json:"format"`
	CoverPath   string      `json:"cover_path"`
	AuthorNames interface{} `json:"author_names"`
}

func (q *Queries) ListRecentProgressByUserID(ctx context.Context, arg ListRecentProgressByUserIDParams) ([]ListRecentProgressByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentProgressByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentProgressByUserIDRow
	for rows.Next() {
		var i ListRecentProgressByUserIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.BookID,
			&i.Location,
			&i.Progress,
			&i.CurrentPage,
			&i.TotalPages,
			&i.IsFinished,
			&i.UpdatedAt,
			&i.Title,
			&i.FilePath,
			&i.FileSize,
			&i.Format,
			&i.CoverPath,
			&i.AuthorNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesWithBookCount = `-- name: ListSeriesWithBookCount :many

SELECT b.series, COUNT(b.id) as book_count
FROM books b
WHERE b.series != ''
GROUP BY b.series COLLATE NOCASE
ORDER BY b.series COLLATE NOCASE ASC
`

type ListSeriesWithBookCountRow struct {
	Series    string `json:"series"`
	BookCount int64  `json:"book_count"`
}

// ============================================================================
// Series Queries
// ============================================================================
func (q *Queries) ListSeriesWithBookCount(ctx context.Context) ([]ListSeriesWithBookCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesWithBookCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesWithBookCountRow
	for rows.Next() {
		var i ListSeriesWithBookCountRow
		if err := rows.Scan(&i.Series, &i.BookCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShelvesForUser = `-- name: ListShelvesForUser :many
SELECT 
    s.id, s.user_id, s.name, s.description, s.is_public, s.created_at, s.updated_at,
    u.username as owner_username,
    u.display_name as owner_display_name,
    COUNT(sb.book_id) as book_count
FROM shelves s
JOIN users u ON s.user_id = u.id
LEFT JOIN shelf_books sb ON s.id = sb.shelf_id
WHERE s.user_id = ? OR s.is_public = 1
GROUP BY s.id
ORDER BY s.is_public ASC, s.name ASC
`

type ListShelvesForUserRow struct {
	ID               int64     `json:"id"`
	UserID           int64     `json:"user_id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	IsPublic         int64     `json:"is_public"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	OwnerUsername    string    `json:"owner_username"`
	OwnerDisplayName string    `json:"owner_display_name"`
	BookCount        int64     `json:"book_count"`
}

func (q *Queries) ListShelvesForUser(ctx context.Context, userID int64) ([]ListShelvesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listShelvesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShelvesForUserRow
	for rows.Next() {
		var i ListShelvesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUsername,
			&i.OwnerDisplayName,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, t.created_at, COUNT(bt.book_id) as book_count
FROM tags t
LEFT JOIN book_tags bt ON t.id = bt.tag_id
GROUP BY t.id
ORDER BY book_count DESC, t.name ASC
`

type ListTagsRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	BookCount int64     `json:"book_count"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, display_name,
       can_read, can_download, can_upload, can_edit, can_delete,
       created_at, updated_at
FROM users
ORDER BY id ASC
`

type ListUsersRow struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	Role        string    `json:"role"`
	DisplayName string    `json:"display_name"`
	CanRead     int64     `json:"can_read"`
	CanDownload int64     `json:"can_download"`
	CanUpload   int64     `json:"can_upload"`
	CanEdit     int64     `json:"can_edit"`
	CanDelete   int64     `json:"can_delete"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.DisplayName,
			&i.CanRead,
			&i.CanDownload,
			&i.CanUpload,
			&i.CanEdit,
			&i.CanDelete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookFromShelf = `-- name: RemoveBookFromShelf :exec
DELETE FROM shelf_books
WHERE shelf_id = ? AND book_id = ?
`

type RemoveBookFromShelfParams struct {
	ShelfID int64 `json:"shelf_id"`
	BookID  int64 `json:"book_id"`
}

func (q *Queries) RemoveBookFromShelf(ctx context.Context, arg RemoveBookFromShelfParams) error {
	_, err := q.db.ExecContext(ctx, removeBookFromShelf, arg.ShelfID, arg.BookID)
	return err
}

const searchBooksFTS = `-- name: SearchBooksFTS :many
SELECT b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format, b.description, b.publisher, b.language, b.pub_date, b.series, b.series_index, b.cover_path, b.created_at, b.updated_at
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
WHERE books_fts.fulltext MATCH ?
ORDER BY books_fts.rank
LIMIT ? OFFSET ?
`

type SearchBooksFTSParams struct {
	Fulltext string `json:"fulltext"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) SearchBooksFTS(ctx context.Context, arg SearchBooksFTSParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksFTS, arg.Fulltext, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksFTSWithAuthors = `-- name: SearchBooksFTSWithAuthors :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce(GROUP_CONCAT(a.name, ', '), '') as author_names
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
LEFT JOIN book_authors ba ON b.id = ba.book_id
LEFT JOIN authors a ON ba.author_id = a.id
WHERE books_fts.fulltext MATCH ?
GROUP BY b.id
ORDER BY books_fts.rank
LIMIT ? OFFSET ?
`

type SearchBooksFTSWithAuthorsParams struct {
	Fulltext string `json:"fulltext"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type SearchBooksFTSWithAuthorsRow struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	FilePath    string      `json:"file_path"`
	FileSha256  string      `json:"file_sha256"`
	FileSize    int64       `json:"file_size"`
	Format      string      `json:"format"`
	Description string      `json:"description"`
	Publisher   string      `json:"publisher"`
	Language    string      `json:"language"`
	PubDate     string      `json:"pub_date"`
	Series      string      `json:"series"`
	SeriesIndex float64     `json:"series_index"`
	CoverPath   string      `json:"cover_path"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	AuthorNames interface{} `json:"author_names"`
}

func (q *Queries) SearchBooksFTSWithAuthors(ctx context.Context, arg SearchBooksFTSWithAuthorsParams) ([]SearchBooksFTSWithAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksFTSWithAuthors, arg.Fulltext, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksFTSWithAuthorsRow
	for rows.Next() {
		var i SearchBooksFTSWithAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksFTSWithAuthorsAndProgress = `-- name: SearchBooksFTSWithAuthorsAndProgress :many
SELECT
    b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format,
    b.description, b.publisher, b.language, b.pub_date, b.series,
    b.series_index, b.cover_path, b.created_at, b.updated_at,
    coalesce((SELECT GROUP_CONCAT(a.name, ', ') FROM book_authors ba JOIN authors a ON ba.author_id = a.id WHERE ba.book_id = b.id), '') as author_names,
    coalesce((SELECT GROUP_CONCAT(t.name, ', ') FROM book_tags bt JOIN tags t ON bt.tag_id = t.id WHERE bt.book_id = b.id), '') as tag_names,
    coalesce(rp.progress, 0.0) as user_progress,
    coalesce(rp.is_finished, 0) as user_is_finished
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
LEFT JOIN reading_progress rp ON b.id = rp.book_id AND rp.user_id = ?
WHERE books_fts.fulltext MATCH ?
GROUP BY b.id
ORDER BY books_fts.rank
LIMIT ? OFFSET ?
`

type SearchBooksFTSWithAuthorsAndProgressParams struct {
	UserID   int64  `json:"user_id"`
	Fulltext string `json:"fulltext"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type SearchBooksFTSWithAuthorsAndProgressRow struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	FilePath       string      `json:"file_path"`
	FileSha256     string      `json:"file_sha256"`
	FileSize       int64       `json:"file_size"`
	Format         string      `json:"format"`
	Description    string      `json:"description"`
	Publisher      string      `json:"publisher"`
	Language       string      `json:"language"`
	PubDate        string      `json:"pub_date"`
	Series         string      `json:"series"`
	SeriesIndex    float64     `json:"series_index"`
	CoverPath      string      `json:"cover_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	AuthorNames    interface{} `json:"author_names"`
	TagNames       interface{} `json:"tag_names"`
	UserProgress   float64     `json:"user_progress"`
	UserIsFinished int64       `json:"user_is_finished"`
}

func (q *Queries) SearchBooksFTSWithAuthorsAndProgress(ctx context.Context, arg SearchBooksFTSWithAuthorsAndProgressParams) ([]SearchBooksFTSWithAuthorsAndProgressRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksFTSWithAuthorsAndProgress,
		arg.UserID,
		arg.Fulltext,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksFTSWithAuthorsAndProgressRow
	for rows.Next() {
		var i SearchBooksFTSWithAuthorsAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorNames,
			&i.TagNames,
			&i.UserProgress,
			&i.UserIsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookRating = `-- name: SetBookRating :one

INSERT INTO book_ratings (user_id, book_id, rating, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id, book_id) DO UPDATE SET
    rating = excluded.rating,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, book_id, rating, created_at, updated_at
`

type SetBookRatingParams struct {
	UserID int64 `json:"user_id"`
	BookID int64 `json:"book_id"`
	Rating int64 `json:"rating"`
}

// ============================================================================
// Book Rating Queries
// ============================================================================
func (q *Queries) SetBookRating(ctx context.Context, arg SetBookRatingParams) (BookRating, error) {
	row := q.db.QueryRowContext(ctx, setBookRating, arg.UserID, arg.BookID, arg.Rating)
	var i BookRating
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookMetadata = `-- name: UpdateBookMetadata :one
UPDATE books
SET title = ?,
    description = ?,
    publisher = ?,
    language = ?,
    pub_date = ?,
    series = ?,
    series_index = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at
`

type UpdateBookMetadataParams struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Publisher   string  `json:"publisher"`
	Language    string  `json:"language"`
	PubDate     string  `json:"pub_date"`
	Series      string  `json:"series"`
	SeriesIndex float64 `json:"series_index"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateBookMetadata(ctx context.Context, arg UpdateBookMetadataParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBookMetadata,
		arg.Title,
		arg.Description,
		arg.Publisher,
		arg.Language,
		arg.PubDate,
		arg.Series,
		arg.SeriesIndex,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHighlight = `-- name: UpdateHighlight :one
UPDATE highlights
SET note = ?,
    color = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, book_id, location, selected_text, note, color, created_at, updated_at
`

type UpdateHighlightParams struct {
	Note   string `json:"note"`
	Color  string `json:"color"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) UpdateHighlight(ctx context.Context, arg UpdateHighlightParams) (Highlight, error) {
	row := q.db.QueryRowContext(ctx, updateHighlight,
		arg.Note,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.Location,
		&i.SelectedText,
		&i.Note,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShelf = `-- name: UpdateShelf :one
UPDATE shelves
SET name = ?,
    description = ?,
    is_public = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, name, description, is_public, created_at, updated_at
`

type UpdateShelfParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsPublic    int64  `json:"is_public"`
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
}

func (q *Queries) UpdateShelf(ctx context.Context, arg UpdateShelfParams) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, updateShelf,
		arg.Name,
		arg.Description,
		arg.IsPublic,
		arg.ID,
		arg.UserID,
	)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET display_name = ?,
    role = ?,
    can_read = ?,
    can_download = ?,
    can_upload = ?,
    can_edit = ?,
    can_delete = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at
`

type UpdateUserParams struct {
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	CanRead     int64  `json:"can_read"`
	CanDownload int64  `json:"can_download"`
	CanUpload   int64  `json:"can_upload"`
	CanEdit     int64  `json:"can_edit"`
	CanDelete   int64  `json:"can_delete"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.DisplayName,
		arg.Role,
		arg.CanRead,
		arg.CanDownload,
		arg.CanUpload,
		arg.CanEdit,
		arg.CanDelete,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, password_hash, role, display_name, can_read, can_download, can_upload, can_edit, can_delete, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CanRead,
		&i.CanDownload,
		&i.CanUpload,
		&i.CanEdit,
		&i.CanDelete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProgress = `-- name: UpsertProgress :one
INSERT INTO reading_progress (
    user_id, book_id, location, progress, current_page, total_pages, is_finished, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP
)
ON CONFLICT(user_id, book_id) DO UPDATE SET
    location = excluded.location,
    progress = excluded.progress,
    current_page = excluded.current_page,
    total_pages = excluded.total_pages,
    is_finished = excluded.is_finished,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, book_id, location, progress, current_page, total_pages, is_finished, updated_at
`

type UpsertProgressParams struct {
	UserID      int64   `json:"user_id"`
	BookID      int64   `json:"book_id"`
	Location    string  `json:"location"`
	Progress    float64 `json:"progress"`
	CurrentPage int64   `json:"current_page"`
	TotalPages  int64   `json:"total_pages"`
	IsFinished  int64   `json:"is_finished"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertProgress,
		arg.UserID,
		arg.BookID,
		arg.Location,
		arg.Progress,
		arg.CurrentPage,
		arg.TotalPages,
		arg.IsFinished,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.Location,
		&i.Progress,
		&i.CurrentPage,
		&i.TotalPages,
		&i.IsFinished,
		&i.UpdatedAt,
	)
	return i, err
}
