// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
	"time"
)

const addBookAuthor = `-- name: AddBookAuthor :exec
INSERT INTO book_authors (book_id, author_id, role)
VALUES (?, ?, ?)
ON CONFLICT(book_id, author_id) DO UPDATE SET role=excluded.role
`

type AddBookAuthorParams struct {
	BookID   int64  `json:"book_id"`
	AuthorID int64  `json:"author_id"`
	Role     string `json:"role"`
}

func (q *Queries) AddBookAuthor(ctx context.Context, arg AddBookAuthorParams) error {
	_, err := q.db.ExecContext(ctx, addBookAuthor, arg.BookID, arg.AuthorID, arg.Role)
	return err
}

const clearBookAuthors = `-- name: ClearBookAuthors :exec
DELETE FROM book_authors
WHERE book_id = ?
`

func (q *Queries) ClearBookAuthors(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, clearBookAuthors, bookID)
	return err
}

const countBooks = `-- name: CountBooks :one
SELECT COUNT(*) FROM books
`

func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=excluded.name
RETURNING id, name, created_at
`

func (q *Queries) CreateAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title, file_path, file_sha256, file_size, format,
    description, publisher, language, pub_date, series,
    series_index, cover_path
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
RETURNING id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at
`

type CreateBookParams struct {
	Title       string  `json:"title"`
	FilePath    string  `json:"file_path"`
	FileSha256  string  `json:"file_sha256"`
	FileSize    int64   `json:"file_size"`
	Format      string  `json:"format"`
	Description string  `json:"description"`
	Publisher   string  `json:"publisher"`
	Language    string  `json:"language"`
	PubDate     string  `json:"pub_date"`
	Series      string  `json:"series"`
	SeriesIndex float64 `json:"series_index"`
	CoverPath   string  `json:"cover_path"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.FilePath,
		arg.FileSha256,
		arg.FileSize,
		arg.Format,
		arg.Description,
		arg.Publisher,
		arg.Language,
		arg.PubDate,
		arg.Series,
		arg.SeriesIndex,
		arg.CoverPath,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = ?
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, created_at FROM authors
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuthorByID(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name, created_at FROM authors
WHERE name = ? LIMIT 1
`

func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getAuthorsForBook = `-- name: GetAuthorsForBook :many
SELECT a.id, a.name, a.created_at, ba.role
FROM authors a
JOIN book_authors ba ON a.id = ba.author_id
WHERE ba.book_id = ?
ORDER BY a.name ASC
`

type GetAuthorsForBookRow struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	Role      string    `json:"role"`
}

func (q *Queries) GetAuthorsForBook(ctx context.Context, bookID int64) ([]GetAuthorsForBookRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuthorsForBookRow
	for rows.Next() {
		var i GetAuthorsForBookRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByFilePath = `-- name: GetBookByFilePath :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE file_path = ? LIMIT 1
`

func (q *Queries) GetBookByFilePath(ctx context.Context, filePath string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByFilePath, filePath)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookBySHA256 = `-- name: GetBookBySHA256 :one
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
WHERE file_sha256 = ? LIMIT 1
`

func (q *Queries) GetBookBySHA256(ctx context.Context, fileSha256 string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookBySHA256, fileSha256)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FilePath,
		&i.FileSha256,
		&i.FileSize,
		&i.Format,
		&i.Description,
		&i.Publisher,
		&i.Language,
		&i.PubDate,
		&i.Series,
		&i.SeriesIndex,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, created_at FROM authors
ORDER BY name ASC
LIMIT ? OFFSET ?
`

type ListAuthorsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, file_path, file_sha256, file_size, format, description, publisher, language, pub_date, series, series_index, cover_path, created_at, updated_at FROM books
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListBooksParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksFTS = `-- name: SearchBooksFTS :many
SELECT b.id, b.title, b.file_path, b.file_sha256, b.file_size, b.format, b.description, b.publisher, b.language, b.pub_date, b.series, b.series_index, b.cover_path, b.created_at, b.updated_at
FROM books b
JOIN books_fts ON b.id = books_fts.rowid
WHERE books_fts.fulltext MATCH ?
ORDER BY books_fts.rank
LIMIT ? OFFSET ?
`

type SearchBooksFTSParams struct {
	Fulltext string `json:"fulltext"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

func (q *Queries) SearchBooksFTS(ctx context.Context, arg SearchBooksFTSParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, searchBooksFTS, arg.Fulltext, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FilePath,
			&i.FileSha256,
			&i.FileSize,
			&i.Format,
			&i.Description,
			&i.Publisher,
			&i.Language,
			&i.PubDate,
			&i.Series,
			&i.SeriesIndex,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
